compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: ubuntu14.04
    paths:
      cc: /usr/local/clang-5.0.0/bin/clang
      cxx: /usr/local/clang-5.0.0/bin/clang++
      f77: /usr/bin/gfortran-4.9
      fc: /usr/bin/gfortran-4.9
    spec: clang@5.0.0
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: ubuntu14.04
    paths:
      cc: /usr/bin/gcc-4.9
      cxx: /usr/bin/g++-4.9
      f77: /usr/bin/gfortran-4.9
      fc: /usr/bin/gfortran-4.9
    spec: gcc@4.9.4
    target: x86_64
