packages:
  cmake:
    version: [3.11.0, 3.12.4]
    paths:
      cmake@3.11.0%gcc@4.8.5 arch=linux-ubuntu14-x86_64: /home/travis/.cache/cmake-3.11.0
      cmake@3.11.0%gcc@4.9.4 arch=linux-ubuntu14-x86_64: /home/travis/.cache/cmake-3.11.0
      cmake@3.11.0%gcc@6.4.0 arch=linux-ubuntu14-x86_64: /home/travis/.cache/cmake-3.11.0
      cmake@3.11.0%gcc@7.3.0 arch=linux-ubuntu14-x86_64: /home/travis/.cache/cmake-3.11.0
      cmake@3.11.0%gcc@8.1.0 arch=linux-ubuntu16-x86_64: /home/travis/.cache/cmake-3.11.0
      cmake@3.11.0%clang@5.0.0 arch=linux-ubuntu14-x86_64: /home/travis/.cache/cmake-3.11.0
      cmake@3.11.0%clang@6.0.0 arch=linux-ubuntu16-x86_64: /home/travis/.cache/cmake-3.11.0
      cmake@3.11.0%clang@7.0.0 arch=linux-ubuntu16-x86_64: /home/travis/.cache/cmake-3.11.0
      cmake@3.11.0%clang@9.1.0 arch=darwin-highsierra-x86_64: /Applications/CMake.app/Contents/
      cmake@3.11.0%clang@10.0.0 arch=darwin-highsierra-x86_64: /Applications/CMake.app/Contents/
    buildable: False
  openmpi:
    version: [1.6.5, 1.10.2]
    paths:
      openmpi@1.6.5%gcc@4.8.5 arch=linux-ubuntu14-x86_64: /usr
      openmpi@1.6.5%gcc@4.9.4 arch=linux-ubuntu14-x86_64: /usr
      openmpi@1.6.5%gcc@6.4.0 arch=linux-ubuntu14-x86_64: /usr
      openmpi@1.6.5%gcc@7.3.0 arch=linux-ubuntu14-x86_64: /usr
      openmpi@1.6.5%gcc@8.1.0 arch=linux-ubuntu16-x86_64: /usr
      openmpi@1.6.5%clang@5.0.0 arch=linux-ubuntu14-x86_64: /usr
      openmpi@1.10.2%clang@7.0.0 arch=linux-ubuntu16-x86_64: /usr
    buildable: False
  hdf5:
    version: [1.10.1, 1.8.13]
  adios:
    variants: ~zfp ~sz ~lz4 ~blosc
  python:
    version: [2.7.14, 2.7.15, 3.5.5, 3.6.3, 3.7.1]
    paths:
      python@3.7.1%clang@7.0.0 arch=linux-ubuntu16-x86_64: /home/travis/virtualenv/python3.7
      python@3.6.3%clang@6.0.0 arch=linux-ubuntu16-x86_64: /home/travis/virtualenv/python3.6
      python@2.7.14%clang@5.0.0 arch=linux-ubuntu14-x86_64: /home/travis/virtualenv/python2.7
      python@2.7.14%gcc@7.3.0 arch=linux-ubuntu14-x86_64: /home/travis/virtualenv/python2.7
      python@2.7.14%gcc@6.4.0 arch=linux-ubuntu14-x86_64: /home/travis/virtualenv/python2.7
      python@2.7.14%gcc@4.9.4 arch=linux-ubuntu14-x86_64: /home/travis/virtualenv/python2.7
      python@3.5.5%gcc@4.8.5 arch=linux-ubuntu14-x86_64: /home/travis/virtualenv/python3.5
      python@3.6.3%gcc@6.4.0 arch=linux-ubuntu14-x86_64: /home/travis/virtualenv/python3.6
      python@3.7.1%gcc@8.1.0 arch=linux-ubuntu16-x86_64: /home/travis/virtualenv/python3.7
      python@2.7.15%clang@9.1.0 arch=darwin-highsierra-x86_64: /usr
      python@2.7.15%clang@10.0.0 arch=darwin-highsierra-x86_64: /usr
    buildable: False
  all:
    providers:
      mpi: [openmpi]
    compiler: [clang@5.0.0, clang@6.0.0, clang@7.0.0, clang@9.1.0, clang@10.0.0, gcc@4.8.5, gcc@4.9.4, gcc@6.4.0, gcc@7.3.0]
