language: cpp
sudo: required
dist: trusty

cache:
  apt: true
  directories:
    - $HOME/.cache/spack
  pip: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages: &common_deps
      - gfortran

env:
  global:
    - BUILD: ~/buildTmp
    - CXXFLAGS: "-Wall -Wextra -Woverloaded-virtual -Wshadow"
    - SPACK_ROOT: $HOME/.cache/spack
    - PATH: $PATH:$HOME/.cache/spack/bin

matrix:
  include:
    # Clang 5.0.0
    - env:
        - openPMD_USE_MPI=ON openPMD_USE_HDF5=ON openPMD_USE_ADIOS1=OFF openPMD_USE_ADIOS2=OFF
      compiler: clang
      addons: &mpi_deps
        apt:
          packages:
            - *common_deps
            - libopenmpi-dev
            - openmpi-bin
    - env:
        - openPMD_USE_MPI=OFF openPMD_USE_HDF5=ON openPMD_USE_ADIOS1=OFF openPMD_USE_ADIOS2=OFF
      compiler: clang
    # GCC 4.8.5
    - env:
        - openPMD_USE_MPI=ON openPMD_USE_HDF5=ON openPMD_USE_ADIOS1=OFF openPMD_USE_ADIOS2=OFF
      compiler: gcc
      addons: *mpi_deps
    - env:
        - openPMD_USE_MPI=OFF openPMD_USE_HDF5=ON openPMD_USE_ADIOS1=OFF openPMD_USE_ADIOS2=OFF
      compiler: gcc

install:
  - SPACK_FOUND=$(which spack >/dev/null && { echo 0; } || { echo 1; })
  - if [ $SPACK_FOUND -ne 0 ]; then
      mkdir -p $SPACK_ROOT &&
      git clone --depth 50 https://github.com/spack/spack.git $SPACK_ROOT &&
      cp $TRAVIS_BUILD_DIR/.travis/spack/*.yaml
         $SPACK_ROOT/etc/spack/ &&
      spack bootstrap;
    fi
  - source /etc/profile &&
    source $SPACK_ROOT/share/spack/setup-env.sh
  - COMPILERSPEC="%$CC"
  - SPACK_VAR_MPI="~mpi";
  # required dependencies - CMake 3.10.0 & Boost 1.62.0
  - travis_wait spack install
      cmake@3.10.0~openssl~ncurses
      $COMPILERSPEC
  - spack load cmake@3.10.0 $COMPILERSPEC
  - travis_wait spack install
      boost@1.62.0
      $COMPILERSPEC
  - spack load boost@1.62.0 $COMPILERSPEC
  # optional dependencies - MPI, HDF5, ADIOS1, ADIOS2
  - if [ $openPMD_USE_MPI == "ON" ]; then
      travis_wait spack install
        openmpi@1.6.5
        $COMPILERSPEC &&
      spack load openmpi@1.6.5 $COMPILERSPEC;
      SPACK_VAR_MPI="+mpi";
    fi
  - if [ $openPMD_USE_HDF5 == "ON" ]; then
      travis_wait spack install
        hdf5
        $SPACK_VAR_MPI
        $COMPILERSPEC &&
      spack load hdf5 $SPACK_VAR_MPI $COMPILERSPEC;
    fi
  - if [ $openPMD_USE_ADIOS1 == "ON" ]; then
      travis_wait spack install
        adios
        $SPACK_VAR_MPI
        $COMPILERSPEC &&
      spack load adios $SPACK_VAR_MPI $COMPILERSPEC;
    fi
  - if [ $openPMD_USE_ADIOS2 == "ON" ]; then
      travis_wait spack install
        adios2
        $SPACK_VAR_MPI
        $COMPILERSPEC &&
      spack load adios2 $SPACK_VAR_MPI $COMPILERSPEC;
    fi
  - spack clean -a

script:
  - mkdir -p $HOME/build 
  - cd $HOME/build
  - CXXFLAGS=$CXXFLAGS CXX=$CXX CC=$CC
    cmake
      -DCMAKE_BUILD_TYPE=Debug
      -DopenPMD_USE_MPI=$openPMD_USE_MPI
      -DopenPMD_USE_HDF5=$openPMD_USE_HDF5
      -DopenPMD_USE_ADIOS1=$openPMD_USE_ADIOS1
      -DopenPMD_USE_ADIOS2=$openPMD_USE_ADIOS2
      -DCMAKE_INSTALL_PREFIX=$HOME/openPMD-test-install
      $TRAVIS_BUILD_DIR
  - make -j 2
  - CTEST_OUTPUT_ON_FAILURE=1 make test
  - make install
  # - make package
  # - dpkg -i openPMD*.deb
