language: cpp
os: linux
dist: xenial
sudo: false

services:
  - docker

compiler:
  - gcc
  - clang

#env:
#  matrix:
#    - PARALLEL=ON
#    - PARALLEL=OFF

script:
  - docker build --build-arg CXX=$CXX .